# Generated by Django 3.2.7 on 2022-03-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('street', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('biography', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TradeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('yearFounder', models.IntegerField()),
                ('yearFounderUnit', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=64)),
                ('material', models.CharField(max_length=64)),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.trademark')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.address')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=64)),
                ('memories', models.CharField(max_length=64)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.os')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.trademark')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('ram', models.CharField(max_length=64)),
                ('memories', models.CharField(max_length=64)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.os')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.trademark')),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.IntegerField()),
                ('insuranceUnit', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('weightUnit', models.CharField(max_length=64)),
                ('productionAdress', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.trademark')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
                ('material', models.CharField(max_length=64)),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.trademark')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=64)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=64)),
                ('yearPublisher', models.CharField(max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.publisher')),
            ],
        ),
    ]
